export enum CaretakerAlgorithmEnum {
  'LOW_NEEDS' = 'LOW_NEEDS',
  'LOW_NEEDS_WITH_RED_FLAGS' = 'LOW_NEEDS_WITH_RED_FLAGS',
  'HIGH_NEEDS' = 'HIGH_NEEDS',
  'HIGH_NEEDS_WITH_RED_FLAGS' = 'HIGH_NEEDS_WITH_RED_FLAGS',
}
