export enum CertificationServiceActions {
  SUCCESSFUL_CERTIFICATION_CREATION,
  UNSUCCESSFUL_CERTIFICATION_CREATION,
  SUCCESSFUL_CERTIFICATION_UPDATE,
  UNSUCCESSFUL_CERTIFICATION_UPDATE,
  SUCCESSFUL_CERTIFICATION_DELETION,
  UNSUCCESSFUL_CERTIFICATION_DELETION,
}
