export enum ClientServiceActions {
  SUCCESSFUL_CLIENT_CREATION,
  UNSUCCESSFUL_CLIENT_CREATION,
  SUCCESSFUL_CLIENT_UPDATE,
  UNSUCCESSFUL_CLIENT_UPDATE,
  SUCCESSFUL_CLIENT_DELETION,
  UNSUCCESSFUL_CLIENT_DELETION,
}
