export enum AssessorActions {
  SUCCESSFUL_ASSESSOR_CREATION,
  UNSUCCESSFUL_ASSESSOR_CREATION,
  SUCCESSFUL_ASSESSOR_UPDATE,
  UNSUCCESSFUL_ASSESSOR_UPDATE,
  SUCCESSFUL_ASSESSOR_DELETION,
  UNSUCCESSFUL_ASSESSOR_DELETION,
}
