export enum CaretakersServiceActions {
  SUCCESSFUL_STATUS_TOGGLE,
  UNSUCCESSFUL_STATUS_TOGGLE,
  SUCCESSFUL_CARETAKER_CREATION,
  UNSUCCESSFUL_CARETAKER_CREATION,
  SUCCESSFUL_CARETAKER_DELETION,
  UNSUCCESSFUL_CARETAKER_DELETION,
}
